#!/usr/bin/env python3

from lib.banner import banner
import sys
import os
import re
import hashlib
import itertools


commands = ["help", "analysis", "crack", "report", "options", "use", "set"]

def main():

	banner()

	while True:
		try:
			arg = input("cr4ckalysis> ")
			if arg == "exit":
				print("Exiting program...")
				exit()
			else:
				command = arg.split(" ")[0]
				para = arg.split(" ")[1:]

				if command not in commands:
					print("Command not found, type 'help' to open user manual.")
				print(' '.join(para[0:]))

		except KeyboardInterrupt:
			print("\nKeyboard Interrupt. Exiting program...")
			exit()

if __name__ == "__main__":
	main()
